"""2-nd migration

Revision ID: 95f14ceaa081
Revises: 46ada3f7aad7
Create Date: 2023-06-27 20:24:25.525229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f14ceaa081'
down_revision = '46ada3f7aad7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
